/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myaplikasibengkel;

import java.awt.Color;
import java.util.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import org.knowm.xchart.PieChart;
import org.knowm.xchart.PieChartBuilder;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;
import org.knowm.xchart.XYSeries;
import org.knowm.xchart.style.Styler.LegendPosition;

/**
 *
 * @author ubuntu
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        this.formProduk = new Produk();
        initComponents();
        xchartdemo();
        omzetChart();
        trendCHart();
        loadInformation();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lineChartpanel = new javax.swing.JPanel();
        pieChartpanel = new java.awt.Panel();
        panelTotalOmzet = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbtotalOMzet = new javax.swing.JLabel();
        panelItemTerjual = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbItemTerjual = new javax.swing.JLabel();
        panelJUmlahItem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbJumlahItem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbTotalProfit = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selamat Datang di Menu Admin");

        lineChartpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lineChartpanel.setLayout(new java.awt.BorderLayout());

        pieChartpanel.setLayout(new java.awt.BorderLayout());

        panelTotalOmzet.setBackground(new java.awt.Color(0, 255, 255));
        panelTotalOmzet.setForeground(new java.awt.Color(102, 255, 255));
        panelTotalOmzet.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Omzet");
        jLabel1.setOpaque(true);
        panelTotalOmzet.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        lbtotalOMzet.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbtotalOMzet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtotalOMzet.setText("0");
        panelTotalOmzet.add(lbtotalOMzet, java.awt.BorderLayout.CENTER);

        panelItemTerjual.setBackground(new java.awt.Color(51, 255, 51));
        panelItemTerjual.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Item Terjual");
        jLabel2.setOpaque(true);
        panelItemTerjual.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        lbItemTerjual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbItemTerjual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbItemTerjual.setText("0");
        panelItemTerjual.add(lbItemTerjual, java.awt.BorderLayout.CENTER);

        panelJUmlahItem.setBackground(new java.awt.Color(0, 255, 204));
        panelJUmlahItem.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jumlah Item");
        jLabel3.setOpaque(true);
        panelJUmlahItem.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        lbJumlahItem.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbJumlahItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJumlahItem.setText("0");
        panelJUmlahItem.add(lbJumlahItem, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Profit");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        lbTotalProfit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTotalProfit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotalProfit.setText("0");
        jPanel1.add(lbTotalProfit, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Data");

        jMenuItem1.setText("Produk");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("User");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Servis");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Riwayat");

        jMenuItem3.setText("Riwayat Servis");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Riwayat Transaksi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTotalOmzet, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelItemTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelJUmlahItem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lineChartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(pieChartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lineChartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieChartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelItemTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTotalOmzet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelJUmlahItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Produk formProduk =  new Produk();
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        formProduk.setVisible(true);
        formProduk.setDefaultCloseOperation(DISPOSE_ON_CLOSE);        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
Manajemen formUser = new Manajemen();
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        formUser.setVisible(true);
        formUser.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
RiwayatTransaksiServis formTransaksi =  new RiwayatTransaksiServis();
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        formTransaksi.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        formTransaksi.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed
RiwayatTransaksi formRiwayat = new RiwayatTransaksi();
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        formRiwayat.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        formRiwayat.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
jasa_service formJasaServis = new jasa_service();
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        formJasaServis.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        formJasaServis.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
public void xchartdemo() {

    double[] xData = new double[] {0.0 , 1.0 , 2.0};
    double[] yData = new double[] {2.0 , 1.0 , 0.0};
    
    XYChart chart = QuickChart.getChart("Demo Chart", "X", "Y","y(x)",xData, yData);
    chart.getStyler().setChartBackgroundColor(new Color (0,0,0,0));
    lineChartpanel.removeAll();
    XChartPanel chartPanel = new XChartPanel<XYChart>(chart);
    lineChartpanel.add(chartPanel);
    lineChartpanel.validate();
}
    Connection conn = Koneksi.connectDB();
    
    public Map<Integer, List> getOmzet() {
    Map<Integer, List> series = new HashMap();
    double total_omzet = 0;
    double profit = 0;
    String sql = "SELECT t.tgl_transaksi, SUM(p.harga_produk * t.total_item) AS total\n" + "FROM transaksi t JOIN produk p ON t.id_produk=p.id_produk\n" + "GROUP BY t.tgl_transaksi";
    
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            int i = 0;
            
            while (rs.next()) {
                ArrayList<Object> data = new ArrayList<Object>();
                data.add(rs.getDate("tgl_transaksi"));
                data.add(rs.getDouble("total"));
                total_omzet += (rs.getDouble("total"));
                series.put(i, data);
                i++;
                
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
     DecimalFormat df = (DecimalFormat)
     DecimalFormat.getCurrencyInstance();
     DecimalFormatSymbols dfs = new DecimalFormatSymbols();
     dfs.setCurrencySymbol("");
     dfs.setMonetaryDecimalSeparator(',');
     dfs.setGroupingSeparator('.');
     df.setDecimalFormatSymbols(dfs);
     String hasil = "Rp. " + df.format(total_omzet);
     String untung_bersih = "Rp. " + df.format(profit);
     lbtotalOMzet.setText(hasil);
     return series;
    }
    
    public Map<Integer, List> getProfit() {
    Map<Integer, List> series = new HashMap();
    double profit = 0;
    String sql = "SELECT t.tgl_transaksi, SUM((p.harga_produk - p.modal_produk) * t.total_item) AS profit\n" + "FROM transaksi t JOIN produk p ON t.id_produk=p.id_produk\n" + "GROUP BY t.tgl_transaksi";
    
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            int i = 0;
            
            while (rs.next()) {
                ArrayList<Object> data = new ArrayList<Object>();
                data.add(rs.getDate("tgl_transaksi"));
                data.add(rs.getDouble("profit"));
                profit += (rs.getDouble("profit"));
                series.put(i, data);
                i++;
                
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
     DecimalFormat df = (DecimalFormat)
     DecimalFormat.getCurrencyInstance();
     DecimalFormatSymbols dfs = new DecimalFormatSymbols();
     dfs.setCurrencySymbol("");
     dfs.setMonetaryDecimalSeparator(',');
     dfs.setGroupingSeparator('.');
     df.setDecimalFormatSymbols(dfs);
     String untung_bersih = "Rp. " + df.format(profit);
     lbTotalProfit.setText(untung_bersih);
     return series;
    }
    
    public void omzetChart() {
    List <Integer> xData = new ArrayList<Integer>();
    List <Double> yData = new ArrayList<Double>();
    
    List <Integer> exData = new ArrayList<Integer>();
    List <Double> yeData = new ArrayList<Double>();
    
    XYChart chart = new XYChartBuilder().title("Omzet").xAxisTitle("x").yAxisTitle("Y").build();
    
    
    chart.getStyler().setLegendPosition(LegendPosition.InsideNE);
    chart.getStyler().setDefaultSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Line);
    chart.getStyler().setXAxisLabelRotation(45);
    chart.getStyler().setChartBackgroundColor(new Color(0,0,0,0));
    chart.getStyler().setXAxisTitleVisible(false);
    chart.getStyler().setYAxisTitleVisible(false);
    chart.getStyler().setYAxisDecimalPattern("#,###.##");
    
  
    
    Map<Object, Object> xMarkMap = new HashMap();
    Map<Integer, List> omzets = getOmzet();
     Map<Integer, List> profit = getProfit();
        for (Map.Entry<Integer, List> entry : omzets.entrySet()) {
            xData.add (entry.getKey());
            xMarkMap.put(entry.getKey(), entry.getValue().get(0));
            yData.add((Double) entry.getValue().get(1));     
        }
         for (Map.Entry<Integer, List> entry : profit.entrySet()) {
            exData.add (entry.getKey());
            xMarkMap.put(entry.getKey(), entry.getValue().get(0));
            yeData.add((Double) entry.getValue().get(1));     
        }
        chart.addSeries("Omzet", xData, yData);
        chart.addSeries("Profit",exData,yeData);
        chart.setCustomXAxisTickLabelsMap(xMarkMap);
      
        lineChartpanel.removeAll();
        XChartPanel chartPanel = new XChartPanel<XYChart>(chart);
        lineChartpanel.add(chartPanel);
        lineChartpanel.validate();
    }
    public Map getTrend() {
    Map<String, Integer> series = new HashMap();
    int total_item = 0;
    String sql = "SELECT SUM(t.total_item)as total, p.nm_produk FROM transaksi t\n" + "JOIN produk p ON t.id_produk = p.id_produk\n" + "GROUP BY t.id_produk";
    
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            int i =0;
            while (rs.next()) {
            series.put(rs.getString("nm_produk"), rs.getInt("total"));
            total_item += rs.getInt("total");
            i++;
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    lbItemTerjual.setText(String.valueOf(total_item));
    return series;
    }
    
    public void trendCHart () {
    PieChart chart = new PieChartBuilder().title("Trend Produk").build();
    
    chart.getStyler().setChartBackgroundColor(new Color(0,0,0,0));
    Map<String, Integer> trends = getTrend();
    
        for (Map.Entry<String, Integer> entry : trends.entrySet()) {
            chart.addSeries(entry.getKey(), entry.getValue());
            
        }
        pieChartpanel.removeAll();
        XChartPanel chartPanel = new XChartPanel<PieChart>(chart);
        pieChartpanel.add(chartPanel);
        pieChartpanel.validate();
    }
     public void loadInformation () {
    String sql = "SELECT COUNT(produk.nm_produk) AS total FROM produk";
    int jumlah_item = 0;
    
    
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            int i =0;
            while (rs.next()) {
            jumlah_item = rs.getInt("total");
            i++;
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        lbJumlahItem.setText(String.valueOf(jumlah_item));
    }
    

    
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbItemTerjual;
    private javax.swing.JLabel lbJumlahItem;
    private javax.swing.JLabel lbTotalProfit;
    private javax.swing.JLabel lbtotalOMzet;
    private javax.swing.JPanel lineChartpanel;
    private javax.swing.JPanel panelItemTerjual;
    private javax.swing.JPanel panelJUmlahItem;
    private javax.swing.JPanel panelTotalOmzet;
    private java.awt.Panel pieChartpanel;
    // End of variables declaration//GEN-END:variables
}
