/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myaplikasibengkel;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static mysqlapp.Koneksi.conn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author liza
 */
public class Service extends javax.swing.JDialog {
    String id_service;
    
   


    /**
     * Creates new form Service
     */
    public Service(java.awt.Frame parent, boolean modal) {
    //    super(parent, modal);
        initComponents();
        autoNumber();
        tampilNamaServices();
        inisialisasi();
        id_service = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnBuatBaru = new javax.swing.JButton();
        txtJumlah = new javax.swing.JTextField();
        cmbServices = new javax.swing.JComboBox<>();
        rb5 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lbNoServis = new javax.swing.JLabel();
        rb0 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servis");
        setLocation(new java.awt.Point(500, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysqlapp/gambar/icon.png"))); // NOI18N
        jLabel1.setText("BENGKEL COY");
        jLabel1.setFont(new java.awt.Font("TeX Gyre Schola Math", 1, 48)); // NOI18N

        jLabel2.setText("No. Services");

        jLabel3.setText("Services");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Discount");

        btnTambah.setText("Cetak");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBuatBaru.setText("Buat Baru");
        btnBuatBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatBaruActionPerformed(evt);
            }
        });

        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahKeyPressed(evt);
            }
        });

        cmbServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbServicesMouseClicked(evt);
            }
        });
        cmbServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServicesActionPerformed(evt);
            }
        });

        btnGrup.add(rb5);
        rb5.setText("5%");

        btnGrup.add(rb10);
        rb10.setText("10%");

        btnGrup.add(rb15);
        rb15.setText("15%");

        jLabel7.setText("Harga");

        jLabel8.setText("Rp. ");

        lblHarga.setText("0");

        lbNoServis.setText("000000");
        lbNoServis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        btnGrup.add(rb0);
        rb0.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rb0)
                                                .addGap(14, 14, 14)
                                                .addComponent(rb5)
                                                .addGap(18, 18, 18)
                                                .addComponent(rb10)
                                                .addGap(18, 18, 18)
                                                .addComponent(rb15))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbServices, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbNoServis)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnBuatBaru)))))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuatBaru)
                    .addComponent(lbNoServis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(lblHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rb5)
                    .addComponent(rb10)
                    .addComponent(rb15)
                    .addComponent(rb0))
                .addGap(18, 18, 18)
                .addComponent(btnTambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
      try {
            // TODO add your handling code here:
            tambahData();
        } catch (JRException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void cmbServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServicesActionPerformed
        // TODO add your handling code here:
        detilServices();
        cariData();
    }//GEN-LAST:event_cmbServicesActionPerformed

    private void btnBuatBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatBaruActionPerformed
        // TODO add your handling code here:
        autoNumber();
        bersih();
        inisialisasi();
    }//GEN-LAST:event_btnBuatBaruActionPerformed

    private void cmbServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbServicesMouseClicked
        // TODO add your handling code here:
       if (evt.getClickCount()==1){
            int discount = 0;
            if (rb0.isSelected()){
            discount = 0;
            }
            if (rb5.isSelected()) {
                discount = 5;
           
            }
            if (rb10.isSelected()) {
                discount = 10;
            }
            if (rb5.isSelected()) {
                discount = 15;
            }
            
            try{
              String sql = "INSERT INTO isi_temp"+ "(no_services, id_services, harga, jml_item, discount) VALUES (?, ? , ? , ?, ?) ";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, lbNoServis.getText());
                stmt.setString(2, (String) cmbServices.getSelectedItem());
                stmt.setString(3, lblHarga.getText());
                stmt.setString(4, txtJumlah.getText());
                stmt.setInt(5, discount);
                
                stmt.executeUpdate();
            } catch(SQLException e ){
                    System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_cmbServicesMouseClicked

    private void txtJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyPressed
        // TODO add your handling code here:
        String jumlah = txtJumlah.getText();
        int l = jumlah.length();
        
         if ( (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') && l < 4 ||evt.getKeyChar() == KeyEvent.VK_ENTER || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) {
                    txtJumlah.setEditable(true);
                } else {
                    txtJumlah.setEditable(false);
                    if ( l == 4 ) {
                    JOptionPane.showMessageDialog(this, "Jumlah tidak valid");
                    }else{
                    JOptionPane.showMessageDialog(this, "Inputan harus angka");
                    }
                }
    }//GEN-LAST:event_txtJumlahKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Service dialog = new Service(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBuatBaru;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbServices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb0;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNoServices;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel lblHarga;
    private JLabel lbNoServis;
    private javax.swing.ButtonGroup btnGrup;
    // End of variables declaration                   
    
    //String id_produk = "";
   // String id_service = "SELECT id_service FROM data_service";
    private void autoNumber() {
    //String noServices = "SER000";
    int i = 0;
            try{
                Connection conn = Koneksi.connectDB();
                Statement st = conn.createStatement();
                String sql = "SELECT * FROM isi ORDER BY no_services DESC" ;
                ResultSet rs = st.executeQuery(sql);
                   if (rs.next()) {
                String nofak = rs.getString("no_services").substring(1);
                String AN ="" + (Integer.parseInt(nofak)+1);
                String Nol ="";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}

              lbNoServis.setText("S" + Nol + AN);
            } else {
              lbNoServis.setText("S0001");
            }
                   rs.close();
                   st.close();
            // txtNoServices.setText(noServices); 
               
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
    }
    
    private void tampilNamaServices() {
        try {
                Connection conn = Koneksi.connectDB();
                Statement st = conn.createStatement();
                String sql = "SELECT nm_services FROM data_service order by nm_services";
                ResultSet rs = st.executeQuery(sql);
                
                while (rs.next()) {
                    cmbServices.addItem(rs.getString("nm_services"));
                    
                }
                conn.close();
                st.close();
        } catch (Exception e) {
        System.out.println(e.getMessage());
        }
    }
    
    
    private void detilServices() {
        try {
                Connection conn = Koneksi.connectDB();
                
                String sql = "SELECT * FROM data_service where nm_services = ? ;";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, (String) cmbServices.getSelectedItem());
                ResultSet rs = st.executeQuery();
                
                if (rs.next()) {
                lblHarga.setText(rs.getString("harga"));
                id_service = rs.getString("id_service");
                } 
                conn.close();
                st.close();
                System.out.println(""+ id_service);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void inisialisasi (){
    btnTambah.setEnabled(false);
    }
    
    private void tambahData()throws JRException {
    int discount = 0;
    int jml_bayar = 0;
        
        if (rb0.isSelected()){
            discount = 0;
        }
        if (rb5.isSelected()) {
            discount = 5;
        }
        if (rb10.isSelected()) {
            discount = 10;
        }
        if (rb15.isSelected()) {
            discount = 15;
        }
        jml_bayar = Integer.parseInt(lblHarga.getText()) * Integer.parseInt(txtJumlah.getText());
        jml_bayar = jml_bayar - (jml_bayar *discount/100);
         
        int nextKode = getNextKode();
        try {
                Connection conn = Koneksi.connectDB();
                Statement st = conn.createStatement();
                 try{
                        String sql = "INSERT INTO isi_temp"
                              + "(no_services, nm_services, id_service, harga, jml_item, discount, jml_bayar) VALUES ( ?, ? , ? , ?, ?, ?, ?)";
                        
                        PreparedStatement stmt = conn.prepareStatement(sql);
                        stmt.setString(1,  lbNoServis.getText());
                        stmt.setString(2, (String) cmbServices.getSelectedItem());
                        stmt.setString(3, id_service);
                        stmt.setString(4, lblHarga.getText());
                        stmt.setString(5, txtJumlah.getText() );
                        stmt.setInt(6, discount);
                        stmt.setInt(7, jml_bayar);
                        stmt.executeUpdate();
                      } catch(SQLException e ){
                              System.out.println(e.getMessage());
                      }
                cetak(String.format("%05d", nextKode));
                String sql = "INSERT INTO isi(no_services," + "id_service," + "jml_item," +"discount, jml_bayar)SELECT no_services,id_service,jml_item, discount, jml_bayar FROM isi_temp";
                st.executeUpdate (sql); 
                st.executeUpdate("DELETE FROM isi_temp");
                
                int sukses = st.executeUpdate(sql);
                
                if (sukses > 0) {
//                    JOptionPane.showMessageDialog(rootPane, "S");
            } else {
//                JOptionPane.showMessageDialog(rootPane, "Data Berhasil di Tambahkan");
                }
                conn.close();
                st.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void cariData() {
        try {
            Connection conn = Koneksi.connectDB();
            String sql = "SELECT * FROM isi WHERE no_services = ? and id_service = ? ";    
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, lbNoServis.getText());
            st.setString(2, id_service);
            ResultSet rs = st.executeQuery();
        if (rs.next()) {
            txtJumlah.setText(rs.getString("jml_item"));
            
            if (rs.getString("discount").equals("0")){
            rb0.setSelected(true);
            }
            if (rs.getString("discount").equals("5")) {
            rb5.setSelected(true);
            }
            if (rs.getString("discount").equals("10")) {
            rb10.setSelected(true);
            }
            if (rs.getString("discount").equals("15")) {
            rb15.setSelected(true);
            }
            inisialisasi();
            
        }else{
            inisialisasi();
            btnTambah.setEnabled(true);
            txtJumlah.setText("");
            rb0.setSelected(true);
        }
        conn.close();
        st.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    private void bersih(){
        txtJumlah.setText("");
        rb0.setSelected(true);
        }
        
    
    public void cetak(String txid)throws JRException{
     //   int total = getTotal();
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("TX_ID", txid);
     //   parameters.put("JUMLAH", total);
        try{
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("../report/strukservices.jasper"), parameters, conn);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
            
        }
    }
    

    
    public int getNextKode(){
         String sql = "SELECT * FROM isi order by " + "no_services DESC LIMIT 1";
         int lastKode = 0;
         try {
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql);
             if(rs.first() == true){
                 lastKode = rs.getInt("no_services");
             }
         } catch (SQLException e){
             System.out.println(e.getMessage());
         }
    return lastKode+1;
    } 
              
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuatBaru;
    private javax.swing.ButtonGroup btnGrup;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbServices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbNoServis;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JRadioButton rb0;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables

*/
}
